### ISSUE TITLE
node-pre-gyp ERR! install response status 404 Not Found

### ISSUE THREAD

**Issue by ayelsew** [kakxem/node-pipewire#10]
After run `npm install node-pipewire`, the follow message is throwed:

![image](https://github.com/kakxem/node-pipewire/assets/33585141/171dce74-fd9a-4956-bcd4-31078ee5f30b)

I saw that it try to download the file `node-v108-linux-x64.tar.gz` but in the release *1.0.15* we have only the `node-v115-linux-arm64.tar.gz

![image](https://github.com/kakxem/node-pipewire/assets/33585141/55fc4135-2a1c-41b7-89ea-0837c7d48179)

Could you fix the file name, please?

**Comment by kakxem** [comment]
Hi, the vXXX indicates the version of NodeJS at the time the package was built, it is not a name I decided on.

- `v108` is for Node 18 LTS
- `v115` is for Node 20 LTS

I [uploaded the `v108`](https://github.com/kakxem/node-pipewire/releases/tag/1.0.15), but I suggest you update to the [next Node LTS version](https://nodejs.org/en/about/previous-releases) because Node 18 is in maintenance and the next version I will make it LTS compatible only.

Thanks for your bug report!
