### ISSUE TITLE
`linkNodesNameToId` and `linkPorts` seem not always link the nodes / ports

### ISSUE THREAD

**Issue by ianwijma** [kakxem/node-pipewire#5]
First off, thanks for providing some layer around the pipewire API. It's much appreciated! 

Now to the issue.

I've written a small program that connects 2 nodes based on some criteria:
- `PipewireEvents` - A class that listens to additions and removals of nodes, ports, links, you name it.
- `Reconnector` - A class that uses the pipewireEvents to register and unregister nodes and if the source and target requirements are met, it lays a connection between the 2 nodes.

The use of this program is for programs whose nodes appear and disappear. For example, in CSGO, the mic input node only appears when pressing the mic is active. 

The issue I have now is that the `linkNodesNameToId` and `linkPorts` do not always link the 2 nodes up. Sometimes being ~ 50% of the time. Which if I don't understand something fully, it should always connect.

---

The code can be found in this repo: https://github.com/ianwijma/pipewire-reconnector/
- `PipesireEvents` - https://github.com/ianwijma/pipewire-reconnector/blob/develop/src/Utilities/PipewireEvents.js
- `Reconnection` - https://github.com/ianwijma/pipewire-reconnector/blob/develop/src/Utilities/Reconnector.js

**Comment by kakxem** [comment]
I apologize for not replying earlier. 

Regarding your issue, I'm uncertain why it's occurring since, as you can see in the Rust code, [I use a for loop](https://github.com/kakxem/node-pipewire/blob/4a5aa49a15780bcabfe3f5bb252c6d590ea91486/src/pipewire_thread.rs#L479-L515) to link nodes by name to id. 

Unfortunately, without access to your logs, I'm unable to pinpoint the problem in the implementation. To help with that, you may pass a 'true' boolean in your [createPwThread() function](https://github.com/kakxem/node-pipewire/blob/4a5aa49a15780bcabfe3f5bb252c6d590ea91486/README.md?plain=1#L67). 

This should enable me to better assist you once you provide the logs. Please let me know if you have any further questions.

**Comment by kakxem** [comment]
I haven't received any response, so I will proceed to close this matter.

If you have any other issues or questions, please don't hesitate to open a new issue.
